"""add sku_mappings table and tiktok order fields

Revision ID: f3a9c1d7e802
Revises: e74b68250e70
Create Date: 2026-08-30 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f3a9c1d7e802'
down_revision: Union[str, None] = 'e74b68250e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sku_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('tiktok_sku', sa.String(length=100), nullable=False),
    sa.Column('variation', sa.String(length=255), nullable=True),
    sa.Column('amazon_sku', sa.String(length=100), nullable=True),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'tiktok_sku', 'variation', name='uq_org_tiktok_sku_variation')
    )
    op.create_index(op.f('ix_sku_mappings_organization_id'), 'sku_mappings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sku_mappings_tiktok_sku'), 'sku_mappings', ['tiktok_sku'], unique=False)

    op.add_column('fulfillment_orders', sa.Column('tiktok_order_id', sa.String(length=255), nullable=True))
    op.add_column('fulfillment_orders', sa.Column('variation', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_fulfillment_orders_tiktok_order_id'), 'fulfillment_orders', ['tiktok_order_id'], unique=False)
    op.create_unique_constraint('uq_org_tiktok_order_id', 'fulfillment_orders', ['organization_id', 'tiktok_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_org_tiktok_order_id', 'fulfillment_orders', type_='unique')
    op.drop_index(op.f('ix_fulfillment_orders_tiktok_order_id'), table_name='fulfillment_orders')
    op.drop_column('fulfillment_orders', 'variation')
    op.drop_column('fulfillment_orders', 'tiktok_order_id')

    op.drop_index(op.f('ix_sku_mappings_tiktok_sku'), table_name='sku_mappings')
    op.drop_index(op.f('ix_sku_mappings_organization_id'), table_name='sku_mappings')
    op.drop_table('sku_mappings')
    # ### end Alembic commands ###
